catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0
minimumReleaseAgeExclude:
  - "@clerk/react@6.15.0"
  - "@clerk/shared@4.31.0"
overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
