spring.application.name=course-service

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/course_service}
spring.datasource.username=${DATABASE_USERNAME:course_service}
spring.datasource.password=${DATABASE_PASSWORD:course_service}
