spring.application.name=ingestion-service

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/ingestion_service}
spring.datasource.username=${DATABASE_USERNAME:ingestion_service}
spring.datasource.password=${DATABASE_PASSWORD:ingestion_service}
