spring.application.name=watchlist-service

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/watchlist_service}
spring.datasource.username=${DATABASE_USERNAME:watchlist_service}
spring.datasource.password=${DATABASE_PASSWORD:watchlist_service}
