spring.application.name=notification-service

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/notification_service}
spring.datasource.username=${DATABASE_USERNAME:notification_service}
spring.datasource.password=${DATABASE_PASSWORD:notification_service}
